### ISSUE TITLE
Can't find the extension in the marketplace

### ISSUE THREAD

**Issue by belkka** [gnramsay/vscode-create-python-module#1]
![image](https://user-images.githubusercontent.com/16609579/139896974-fe3944bc-2a70-48e8-acab-a00a462158a9.png)
From https://marketplace.visualstudio.com/items?itemName=gnramsay.create-python-module:

    ext install gnramsay.create-python-module

![image](https://user-images.githubusercontent.com/16609579/139897460-ad8ee8a9-3193-4ec0-990c-525e10601e23.png)

**Comment by seapagan** [comment]
Sorry just saw this, my notifications must be off 😊 

Yeah, that's a strange one, maybe missing some metadata. I'll look at this and fix it. Thanks for the Heads up!

(also I replied from the wrong github account 🤦‍♂️ but this is the author :D)

**Comment by belkka** [comment]
In my case it helped to install another version of vscode from archlinux repo: `pacman -S visual-studio-code-bin`. I have found the solution here: https://github.com/microsoft/vscode/issues/108147

This seems to be an explanation:
> ArchLinux and Manjaro no longer use the VS Code marketplace, but Open VSX. If the extension is not available on Open VSX, it does not appear in the search.

— https://github.com/microsoft/vscode/issues/108147#issuecomment-705510202

**Comment by gnramsay** [comment]
hi @belkka, thanks for the good info. I'll look to upload the extension to the Open VSX today which will hopefully fix this.
Sorry for the delay, been a bit sick.

**Comment by gnramsay** [comment]
The extension is now published on Open VSX, I'm still awaiting confirmation of ownership of the namespace though.

I'll leave this issue open until this is confirmed. Thank you @belkka for bringing this to my attention 😀 

![image](https://user-images.githubusercontent.com/69428076/146347638-050dea3b-b809-4a67-9c4f-a8656073546f.png)

**Comment by gnramsay** [comment]
Namespace ownership is confirmed, so the extension is now fully available on the Open VSX marketplace at https://open-vsx.org/extension/gnramsay/create-python-module.

Closing this issue now.
